const API_BASE="/api";
const tabs=document.querySelectorAll(".tab");
const panels={single:document.getElementById("single-panel"),list:document.getElementById("list-panel"),pdf:document.getElementById("pdf-panel")};
const loading=document.getElementById("loading"),message=document.getElementById("message"),resultsSection=document.getElementById("results-section"),resultsBox=document.getElementById("results"),downloadLink=document.getElementById("download-link");
tabs.forEach(tab=>tab.addEventListener("click",()=>{tabs.forEach(t=>t.classList.remove("active"));tab.classList.add("active");Object.entries(panels).forEach(([m,p])=>p.classList.toggle("hidden",m!==tab.dataset.mode));clearOutput();}));
function clearOutput(){resultsSection.classList.add("hidden");message.classList.add("hidden");message.textContent="";resultsBox.innerHTML="";downloadLink.classList.add("hidden");downloadLink.removeAttribute("href");}
function setLoading(active){loading.classList.toggle("hidden",!active);document.querySelectorAll(".verify-btn").forEach(b=>b.disabled=active);}
function showMessage(text){message.textContent=text;message.classList.remove("hidden");}
function escapeHtml(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
function statusStyle(s){return {"VERIFIED":{color:"#28a745",bg:"#d4edda",icon:"✅"},"UNCERTAIN":{color:"#856404",bg:"#fff3cd",icon:"⚠️"},"NOT VERIFIED":{color:"#721c24",bg:"#f8d7da",icon:"❌"}}[s]||{color:"#383d41",bg:"#e2e3e5",icon:"❔"};}
function renderCard(r){const status=String(r.status||"UNKNOWN").toUpperCase(),style=statusStyle(status),reference=r.original_reference||"",explanation=r.explanation||r.reason||"No explanation available.",source=r.source||"unknown",refNum=r.reference_id??"?",sources=Array.isArray(r.sources_agreeing)?r.sources_agreeing:[];return `<div class="result-card" style="border-left-color:${style.color};background:${style.bg};"><div class="result-title" style="color:${style.color};">[#${escapeHtml(refNum)}] ${style.icon} ${escapeHtml(status)} <span class="result-meta">(via ${escapeHtml(source)})</span></div><div class="result-reference"><b>Reference:</b> ${escapeHtml(reference)}</div><div class="result-why"><b>Why:</b> ${escapeHtml(explanation)}</div>${sources.length?`<div class="result-sources"><b>Sources agreeing:</b> ${sources.map(escapeHtml).join(", ")}</div>`:""}</div>`;}
function showResults(results,url){if(!Array.isArray(results)||!results.length){showMessage("No verification results were returned.");return;}resultsBox.innerHTML=`<p><b>Found ${results.length} reference(s).</b></p>${results.map(renderCard).join("")}`;resultsSection.classList.remove("hidden");if(url){downloadLink.href=url;downloadLink.classList.remove("hidden");}}
async function postJson(endpoint,body){const response=await fetch(`${API_BASE}${endpoint}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok){let d=`Server error (${response.status})`;try{const x=await response.json();d=x.detail||x.message||d;}catch(_){}throw Error(d);}return response.json();}
async function postPdf(file){const fd=new FormData();fd.append("file",file);const response=await fetch(`${API_BASE}/verify/pdf`,{method:"POST",body:fd});if(!response.ok){let d=`Server error (${response.status})`;try{const x=await response.json();d=x.detail||x.message||d;}catch(_){}throw Error(d);}return response.json();}
async function verifySingle(){clearOutput();const reference=document.getElementById("single-input").value.trim();if(!reference)return showMessage("Please enter a reference.");setLoading(true);try{const d=await postJson("/verify/single",{reference});showResults(d.results,d.download_url);}catch(e){showMessage(`❌ ${e.message}`);}finally{setLoading(false);}}
async function verifyList(){clearOutput();const reference_text=document.getElementById("list-input").value.trim();if(!reference_text)return showMessage("Please enter a reference list.");setLoading(true);try{const d=await postJson("/verify/list",{reference_text});showResults(d.results,d.download_url);}catch(e){showMessage(`❌ ${e.message}`);}finally{setLoading(false);}}
async function verifyPdf(){clearOutput();const file=document.getElementById("pdf-input").files[0];if(!file)return showMessage("Please select a PDF.");setLoading(true);try{const d=await postPdf(file);showResults(d.results,d.download_url);}catch(e){showMessage(`❌ ${e.message}`);}finally{setLoading(false);}}
document.getElementById("single-button").addEventListener("click",verifySingle);document.getElementById("list-button").addEventListener("click",verifyList);document.getElementById("pdf-button").addEventListener("click",verifyPdf);
const pdfInput=document.getElementById("pdf-input"),dropZone=document.getElementById("drop-zone"),fileName=document.getElementById("file-name");
pdfInput.addEventListener("change",()=>fileName.textContent=pdfInput.files[0]?pdfInput.files[0].name:"No file selected");
["dragenter","dragover"].forEach(n=>dropZone.addEventListener(n,e=>{e.preventDefault();dropZone.classList.add("dragover");}));
["dragleave","drop"].forEach(n=>dropZone.addEventListener(n,e=>{e.preventDefault();dropZone.classList.remove("dragover");}));
dropZone.addEventListener("drop",e=>{const f=e.dataTransfer.files[0];if(f&&f.type==="application/pdf"){const dt=new DataTransfer();dt.items.add(f);pdfInput.files=dt.files;fileName.textContent=f.name;}else showMessage("Please drop a PDF file.");});
